export const SETTING_KEY = 'TVT__SETTINGS'
export const THEME_ID = 'TVT__THEME'
export const WINSIZE_ID = 'TVT__WINSIZE'
export const LANG_ID = 'TVT__LANG'
export const APPEARANCE_KEY = 'TVT__APPEARANCE'